--set the database and schema context
USE DATABASE OUR_FIRST_DATABASE;
USE SCHEMA A_CUSTOM_SCHEMA;

--create a customer table
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL,
    LAST_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    EMAIL_ADDRESS VARCHAR(100),
    COMPANY_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(100),
    ADDRESS_LINE_1 VARCHAR(150),
    ADDRESS_LINE_2 VARCHAR(150),
    CITY_NAME VARCHAR(100),
    STATE_NAME VARCHAR(100),
    POSTAL_CODE VARCHAR(15),
    COUNTRY_NAME VARCHAR(50)
);

--describe the table structure
DESCRIBE TABLE CUSTOMER;

--recreate the customer table with address columns defined as STRING
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL,
    LAST_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(100),
    EMAIL_ADDRESS VARCHAR(100),
    COMPANY_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(100),
    ADDRESS_LINE_1 STRING,
    ADDRESS_LINE_2 STRING,
    CITY_NAME VARCHAR(100),
    STATE_NAME VARCHAR(100),
    POSTAL_CODE VARCHAR(15),
    COUNTRY_NAME VARCHAR(50)
);

--verify the updated table structure
DESCRIBE TABLE CUSTOMER;

--create a deep copy of the customer table
CREATE OR REPLACE TABLE CUSTOMER_DEEP_COPY
AS
SELECT *
FROM CUSTOMER;

--create a shallow copy of the customer table structure
CREATE OR REPLACE TABLE CUSTOMER_SHALLOW_COPY
LIKE CUSTOMER;

--verify the shallow copy contains no rows
SELECT COUNT(*)
FROM CUSTOMER_SHALLOW_COPY;

--create a temporary table for the current session
CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_TEMP
AS
SELECT *
FROM CUSTOMER
WHERE TRY_TO_NUMBER(POSTAL_CODE) IS NOT NULL;

--create a transient table that persists across sessions without fail-safe storage
CREATE OR REPLACE TRANSIENT TABLE CUSTOMER_TRANS
AS
SELECT *
FROM CUSTOMER
WHERE TRY_TO_NUMBER(POSTAL_CODE) IS NULL;

--compare the created customer tables
SHOW TABLES LIKE 'CUSTOMER%';
