--create a governance database and classification schema
CREATE OR REPLACE DATABASE C10_GOV_DB;
CREATE OR REPLACE SCHEMA C10_GOV_DB.CLASSIFICATION;

--create a sample customer table
CREATE OR REPLACE TABLE C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA
(
    CUSTOMER_ID NUMBER,
    FULL_NAME STRING,
    EMAIL STRING,
    REGION STRING
);

--insert sample customer data
INSERT INTO C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA VALUES
    (1, 'John Smith', 'john.smith@email.com', 'US'),
    (2, 'Jane Doe', 'jane.doe@email.com', 'EU');

--create a tag with allowed sensitivity values
CREATE OR REPLACE TAG C10_GOV_DB.CLASSIFICATION.SENSITIVE_DATA_TAG
    ALLOWED_VALUES 'HIGH', 'MEDIUM', 'LOW';

--assign the tag to the EMAIL column
ALTER TABLE C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA
    MODIFY COLUMN EMAIL
    SET TAG C10_GOV_DB.CLASSIFICATION.SENSITIVE_DATA_TAG = 'HIGH';

--assign the tag to the FULL_NAME column
ALTER TABLE C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA
    MODIFY COLUMN FULL_NAME
    SET TAG C10_GOV_DB.CLASSIFICATION.SENSITIVE_DATA_TAG = 'MEDIUM';

--view column-level tag assignments
SELECT *
FROM TABLE(
    C10_GOV_DB.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
        'C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA',
        'TABLE'
    )
);
