--create and set the database
CREATE OR REPLACE DATABASE C9_R8;

USE DATABASE C9_R8;
USE SCHEMA PUBLIC;

--create a structured user-defined type for dimension metadata
CREATE OR REPLACE TYPE DIMENSION_METADATA AS OBJECT
(
    EFFECTIVE_START_DT DATE,
    EFFECTIVE_END_DT DATE,
    IS_CURRENT BOOLEAN,
    CREATED_TS TIMESTAMP_NTZ,
    UPDATED_TS TIMESTAMP_NTZ,
    SOURCE_SYSTEM_CD VARCHAR(25),
    LOAD_BATCH_ID NUMBER(18,0)
);

--create a dimension table that uses the structured type
CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID VARCHAR(50),
    CUSTOMER_NAME VARCHAR(100),
    METADATA DIMENSION_METADATA
);

--review the table structure
DESCRIBE TABLE DIM_CUSTOMER;

--insert sample dimension rows with typed metadata objects
INSERT INTO DIM_CUSTOMER
SELECT
    1,
    'C1001',
    'ACME INDUSTRIES',
    OBJECT_CONSTRUCT(
        'EFFECTIVE_START_DT', '2025-01-01'::DATE,
        'EFFECTIVE_END_DT', '9999-12-31'::DATE,
        'IS_CURRENT', TRUE,
        'CREATED_TS', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        'UPDATED_TS', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        'SOURCE_SYSTEM_CD', 'ERP',
        'LOAD_BATCH_ID', 1001::NUMBER(18,0)
    )::DIMENSION_METADATA
UNION ALL
SELECT
    2,
    'C1002',
    'NORTHWIND RETAIL',
    OBJECT_CONSTRUCT(
        'EFFECTIVE_START_DT', '2025-02-01'::DATE,
        'EFFECTIVE_END_DT', '9999-12-31'::DATE,
        'IS_CURRENT', TRUE,
        'CREATED_TS', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        'UPDATED_TS', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
        'SOURCE_SYSTEM_CD', 'CRM',
        'LOAD_BATCH_ID', 1002::NUMBER(18,0)
    )::DIMENSION_METADATA;

--query the stored metadata
SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    METADATA
FROM DIM_CUSTOMER;

--query individual metadata attributes using object notation
SELECT
    CUSTOMER_NAME,
    METADATA:EFFECTIVE_START_DT,
    METADATA:IS_CURRENT,
    METADATA:SOURCE_SYSTEM_CD
FROM DIM_CUSTOMER;

--show user-defined types available in the schema
SHOW TYPES;
