--set the schema context
USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL;

--run an intentionally inefficient query
SELECT *
FROM STORE_RETURNS, DATE_DIM
WHERE SR_RETURNED_DATE_SK = D_DATE_SK;

--replace SELECT * with only the required columns
USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL;

SELECT
    D_YEAR,
    SR_CUSTOMER_SK AS CTR_CUSTOMER_SK,
    SR_STORE_SK AS CTR_STORE_SK,
    SR_RETURN_AMT_INC_TAX
FROM STORE_RETURNS, DATE_DIM
WHERE SR_RETURNED_DATE_SK = D_DATE_SK;

--add a filter to reduce partitions scanned
USE SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL;

SELECT
    D_YEAR,
    SR_CUSTOMER_SK AS CTR_CUSTOMER_SK,
    SR_STORE_SK AS CTR_STORE_SK,
    SR_RETURN_AMT_INC_TAX
FROM STORE_RETURNS, DATE_DIM
WHERE SR_RETURNED_DATE_SK = D_DATE_SK
  AND D_YEAR = 1999;
