USE ROLE SYSADMIN;

CREATE DATABASE C6_R1;
CREATE SCHEMA RECIPES;

USE DATABASE C6_R1;
USE SCHEMA RECIPES;

CREATE TABLE CUSTOMER
(
    CUSTOMERID VARCHAR(100),
    FNAME VARCHAR(1024),
    LNAME VARCHAR(1024),
    EMAIL VARCHAR(1024),
    DATE_OF_BIRTH VARCHAR(1024),
    CITY VARCHAR(1024),
    COUNTRY VARCHAR(1024)
);

CREATE FILE FORMAT CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    DATE_FORMAT = 'YYYY-MM-DD';

CREATE OR REPLACE STAGE C6_R1_STAGE
    URL = 's3://snowflake-cookbook/Chapter06/r1'
    FILE_FORMAT = CSV_FORMAT;

LIST @C6_R1_STAGE;

COPY INTO CUSTOMER
FROM @C6_R1_STAGE;

SHOW TABLES;

CREATE TABLE CUSTOMER_OPT
(
    CUSTOMERID DECIMAL(10,0),
    FNAME VARCHAR(50),
    LNAME VARCHAR(50),
    EMAIL VARCHAR(50),
    DATE_OF_BIRTH DATE,
    CITY VARCHAR(50),
    COUNTRY VARCHAR(50)
);

COPY INTO CUSTOMER_OPT
FROM @C6_R1_STAGE;

SHOW TABLES;
