--run the aggregation query used by the task
SELECT
    C.C_NAME,
    SUM(L_EXTENDEDPRICE),
    SUM(L_TAX)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
    ON O.O_CUSTKEY = C.C_CUSTKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LI
    ON LI.L_ORDERKEY = O.O_ORDERKEY
GROUP BY C.C_NAME;

--create a database and target table for task output
CREATE DATABASE TASK_DEMO;
USE DATABASE TASK_DEMO;

CREATE TABLE ORDERING_CUSTOMERS
(
    REPORTING_TIME TIMESTAMP,
    CUSTOMER_NAME STRING,
    REVENUE NUMBER(16,2),
    TAX NUMBER(16,2)
);

--create a scheduled task to refresh the reporting table every 30 minutes
CREATE TASK REFRESH_ORDERING_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '30 MINUTE'
    COMMENT = 'Update Ordering_Customers Table with latest data'
AS
    INSERT INTO ORDERING_CUSTOMERS
    SELECT
        CURRENT_TIMESTAMP,
        C.C_NAME,
        SUM(L_EXTENDEDPRICE),
        SUM(L_TAX)
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
        ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LI
        ON LI.L_ORDERKEY = O.O_ORDERKEY
    GROUP BY CURRENT_TIMESTAMP, C.C_NAME;

--describe the task
DESC TASK REFRESH_ORDERING_CUSTOMERS;

--grant task execution privilege to SYSADMIN
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

--resume the task
ALTER TASK REFRESH_ORDERING_CUSTOMERS RESUME;

--verify the task state
DESC TASK REFRESH_ORDERING_CUSTOMERS;

--query task history
SELECT
    NAME,
    STATE,
    COMPLETED_TIME,
    SCHEDULED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'REFRESH_ORDERING_CUSTOMERS';

--validate task output after execution
SELECT *
FROM ORDERING_CUSTOMERS;
