--grant warehouse usage to the task owner role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

--sample aggregation query
SELECT
    C.C_NAME,
    SUM(L_EXTENDEDPRICE),
    SUM(L_TAX)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
    ON O.O_CUSTKEY = C.C_CUSTKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LI
    ON LI.L_ORDERKEY = O.O_ORDERKEY
GROUP BY C.C_NAME;

--create the target database and table
USE ROLE SYSADMIN;

CREATE DATABASE TASK_DEMO;
USE DATABASE TASK_DEMO;

CREATE TABLE ORDERING_CUSTOMERS
(
    REPORTING_TIME TIMESTAMP,
    CUSTOMER_NAME STRING,
    REVENUE NUMBER(16,2),
    TAX NUMBER(16,2)
);

--create the scheduled task
CREATE TASK REFRESH_ORDERING_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '30 MINUTE'
    COMMENT = 'Update ORDERING_CUSTOMERS table with latest data'
AS
    INSERT INTO ORDERING_CUSTOMERS
    SELECT
        CURRENT_TIMESTAMP,
        C.C_NAME,
        SUM(L_EXTENDEDPRICE),
        SUM(L_TAX)
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
        ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LI
        ON LI.L_ORDERKEY = O.O_ORDERKEY
    GROUP BY CURRENT_TIMESTAMP, C.C_NAME;

--describe the task
DESC TASK REFRESH_ORDERING_CUSTOMERS;

--grant task execution privileges to the role that owns the task
USE ROLE ACCOUNTADMIN;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

--resume the task using the owning role
USE ROLE SYSADMIN;

ALTER TASK REFRESH_ORDERING_CUSTOMERS RESUME;

--confirm task state
DESC TASK REFRESH_ORDERING_CUSTOMERS;

--monitor task history
SELECT
    NAME,
    STATE,
    COMPLETED_TIME,
    SCHEDULED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'REFRESH_ORDERING_CUSTOMERS';

--optional: manually trigger the task for testing
EXECUTE TASK REFRESH_ORDERING_CUSTOMERS;

--validate output
SELECT *
FROM ORDERING_CUSTOMERS;
