USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;

SELECT
    QUERY_ID,
    QUERY_TEXT,
    EXECUTION_TIME,
    USER_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
ORDER BY EXECUTION_TIME DESC;

USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;

SELECT
    QUERY_TEXT,
    USER_NAME,
    HASH(QUERY_TEXT) AS PSEUDO_QUERY_ID,
    COUNT(*) AS NUM_OF_QUERIES,
    SUM(EXECUTION_TIME) AS AGG_EXECUTION_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
GROUP BY QUERY_TEXT, USER_NAME
ORDER BY AGG_EXECUTION_TIME DESC;

SELECT
    QUERY_ID,
    QUERY_TEXT,
    USER_NAME,
    HASH(QUERY_TEXT) AS PSEUDO_QUERY_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE HASH(QUERY_TEXT) = <replace_with_pseudo_query_id>;
