--identify queries with the longest execution time
USE ROLE ACCOUNTADMIN;
USE SNOWFLAKE;

SELECT
    QUERY_ID,
    QUERY_TEXT,
    EXECUTION_TIME,
    USER_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
ORDER BY EXECUTION_TIME DESC;

--aggregate frequently executed queries by query text
USE ROLE ACCOUNTADMIN;
USE SNOWFLAKE;

SELECT
    QUERY_TEXT,
    USER_NAME,
    HASH(QUERY_TEXT) AS PSEUDO_QUERY_ID,
    COUNT(*) AS NUM_OF_QUERIES,
    SUM(EXECUTION_TIME) AS AGG_EXECUTION_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
GROUP BY QUERY_TEXT, USER_NAME
ORDER BY AGG_EXECUTION_TIME DESC;

--find actual query IDs for a pseudo query ID
USE ROLE ACCOUNTADMIN;
USE SNOWFLAKE;

SELECT
    QUERY_ID,
    QUERY_TEXT,
    USER_NAME,
    HASH(QUERY_TEXT) AS PSEUDO_QUERY_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE PSEUDO_QUERY_ID = <replace_with_pseudo_query_id>;
