--create roles to demonstrate masking behavior
USE ROLE USERADMIN;

CREATE OR REPLACE ROLE DATA_FULL_ACCESS;
CREATE OR REPLACE ROLE DATA_LIMITED_ACCESS;

--grant roles to the test user
USE ROLE SECURITYADMIN;

GRANT ROLE DATA_FULL_ACCESS TO USER <your_loginname>;
GRANT ROLE DATA_LIMITED_ACCESS TO USER <your_loginname>;

--grant object access to both roles
GRANT USAGE ON DATABASE C10_GOV_DB TO ROLE DATA_FULL_ACCESS;
GRANT USAGE ON SCHEMA C10_GOV_DB.CLASSIFICATION TO ROLE DATA_FULL_ACCESS;
GRANT SELECT ON TABLE C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA TO ROLE DATA_FULL_ACCESS;

GRANT USAGE ON DATABASE C10_GOV_DB TO ROLE DATA_LIMITED_ACCESS;
GRANT USAGE ON SCHEMA C10_GOV_DB.CLASSIFICATION TO ROLE DATA_LIMITED_ACCESS;
GRANT SELECT ON TABLE C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA TO ROLE DATA_LIMITED_ACCESS;

--create a masking policy for email values
USE ROLE SECURITYADMIN;

CREATE OR REPLACE MASKING POLICY C10_GOV_DB.CLASSIFICATION.EMAIL_MASKING_POLICY
AS (VAL STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'DATA_FULL_ACCESS' THEN VAL
        ELSE '***MASKED***'
    END;

--associate the masking policy with the sensitivity tag
ALTER TAG C10_GOV_DB.CLASSIFICATION.SENSITIVE_DATA_TAG
SET MASKING POLICY C10_GOV_DB.CLASSIFICATION.EMAIL_MASKING_POLICY;

--query the table using the full access role
USE ROLE DATA_FULL_ACCESS;

SELECT *
FROM C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA;

--query the table using the limited access role
USE ROLE DATA_LIMITED_ACCESS;

SELECT *
FROM C10_GOV_DB.CLASSIFICATION.CUSTOMER_DATA;
