CREATE DATABASE C6_R6;
USE DATABASE C6_R6;

CREATE TABLE TRANSACTIONS
(
    TXN_ID STRING,
    TXN_DATE DATE,
    CUSTOMER_ID STRING,
    QUANTITY DECIMAL(20),
    PRICE DECIMAL(30,2),
    COUNTRY_CD STRING
);

--run this statement 8-10 times to create enough data for the example
INSERT INTO TRANSACTIONS
SELECT
    UUID_STRING() AS TXN_ID,
    DATEADD(DAY, UNIFORM(1, 500, RANDOM()) * -1, '2020-10-15') AS TXN_DATE,
    UUID_STRING() AS CUSTOMER_ID,
    UNIFORM(1, 10, RANDOM()) AS QUANTITY,
    UNIFORM(1, 200, RANDOM()) AS PRICE,
    RANDSTR(2, RANDOM()) AS COUNTRY_CD
FROM TABLE(GENERATOR(ROWCOUNT => 10000000));

SELECT *
FROM TRANSACTIONS
WHERE TXN_DATE BETWEEN DATEADD(DAY, -31, '2020-10-15')
                   AND '2020-10-15';

ALTER TABLE TRANSACTIONS CLUSTER BY (TXN_DATE);

SELECT *
FROM TRANSACTIONS
WHERE TXN_DATE BETWEEN DATEADD(DAY, -31, '2020-10-15')
                   AND '2020-10-15';
