--set context to access Snowflake metadata
USE DATABASE SNOWFLAKE;
USE SCHEMA INFORMATION_SCHEMA;

--summarize query activity by hour
SELECT
    DATE_TRUNC('hour', START_TIME) AS QUERY_HOUR,
    COUNT(*) AS TOTAL_QUERIES,
    AVG(TOTAL_ELAPSED_TIME) / 1000 AS AVG_QUERY_SECONDS
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    END_TIME_RANGE_START => DATEADD('day', -6, CURRENT_TIMESTAMP()),
    END_TIME_RANGE_END => CURRENT_TIMESTAMP()
))
GROUP BY 1
ORDER BY 1;

--summarize query activity by warehouse
SELECT
    WAREHOUSE_NAME,
    COUNT(*) AS QUERY_COUNT,
    SUM(TOTAL_ELAPSED_TIME) / 1000 AS TOTAL_QUERY_SECONDS
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    END_TIME_RANGE_START => DATEADD('day', -6, CURRENT_TIMESTAMP()),
    END_TIME_RANGE_END => CURRENT_TIMESTAMP()
))
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_QUERY_SECONDS DESC;

--identify longest-running query activity by warehouse
SELECT
    WAREHOUSE_NAME,
    COUNT(*) AS QUERY_COUNT,
    SUM(TOTAL_ELAPSED_TIME) / 1000 AS TOTAL_QUERY_SECONDS
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    END_TIME_RANGE_START => DATEADD('day', -6, CURRENT_TIMESTAMP()),
    END_TIME_RANGE_END => CURRENT_TIMESTAMP()
))
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_QUERY_SECONDS DESC;
