--create a table with sensitive customer data
USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE GOVERNANCE_DB;
CREATE OR REPLACE SCHEMA GOVERNANCE_DB.SECURITY;

CREATE OR REPLACE TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
(
    CUSTOMER_ID NUMBER,
    FULL_NAME STRING,
    EMAIL STRING,
    REGION STRING
);

INSERT INTO GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
    (CUSTOMER_ID, FULL_NAME, EMAIL, REGION)
VALUES
    (1, 'JANE DOE', 'JANE.DOE@EXAMPLE.COM', 'EAST'),
    (2, 'JOHN DOE', 'JOHN.DOE@EXAMPLE.COM', 'WEST'),
    (3, 'PAT SMITH', 'PAT.SMITH@EXAMPLE.COM', 'EAST');

--create roles for masked and unmasked access
USE ROLE USERADMIN;

CREATE OR REPLACE ROLE PII_MASKED;
CREATE OR REPLACE ROLE PII_FULL;

--grant table access to both roles
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE PII_MASKED;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE PII_MASKED;
GRANT SELECT ON TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA TO ROLE PII_MASKED;

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE PII_FULL;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE PII_FULL;
GRANT SELECT ON TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA TO ROLE PII_FULL;

--grant privileges needed to create and apply masking policies
GRANT CREATE MASKING POLICY ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE SECURITYADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE SECURITYADMIN;

--create a masking policy for the EMAIL column
CREATE OR REPLACE MASKING POLICY GOVERNANCE_DB.SECURITY.EMAIL_MASK
    AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'PII_FULL' THEN VAL
        ELSE '************'
    END;

--apply the masking policy to the EMAIL column
USE ROLE SECURITYADMIN;

ALTER TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
    MODIFY COLUMN EMAIL
    SET MASKING POLICY GOVERNANCE_DB.SECURITY.EMAIL_MASK;

--grant roles to the user used for validation
USE ROLE SECURITYADMIN;

GRANT ROLE PII_MASKED TO USER <YOUR_USER_NAME>;

--for validation in this recipe, also grant PII_FULL to the same user
GRANT ROLE PII_FULL TO USER <YOUR_USER_NAME>;

--validate masked behavior
USE ROLE PII_MASKED;

SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    REGION
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA;

--validate unmasked behavior
USE ROLE PII_FULL;

SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    REGION
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA;
