--create a database for SQL table UDFs
CREATE DATABASE C10_R2;
USE DATABASE C10_R2;
USE SCHEMA PUBLIC;

--call a built-in Snowflake table function
SELECT *
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION())
ORDER BY START_TIME;

--create a simple SQL table UDF
CREATE FUNCTION LOCATIONTIMEZONE()
RETURNS TABLE(LOCATIONNAME STRING, TIMEZONENAME STRING)
AS
$$
    SELECT 'Sydney', 'GMT+11'
    UNION
    SELECT 'Auckland', 'GMT+13'
    UNION
    SELECT 'Islamabad', 'GMT+5'
    UNION
    SELECT 'London', 'GMT'
$$;

--call the SQL table UDF
SELECT *
FROM TABLE(LOCATIONTIMEZONE());

--filter the output of the SQL table UDF
SELECT TIMEZONENAME
FROM TABLE(LOCATIONTIMEZONE())
WHERE LOCATIONNAME = 'Sydney';

--create a SQL table UDF that returns customer order totals
CREATE FUNCTION CUSTOMERORDERS()
RETURNS TABLE(CUSTOMERNAME STRING, TOTALSPENT NUMBER(12,2))
AS
$$
    SELECT
        C.C_NAME AS CUSTOMERNAME,
        SUM(O.O_TOTALPRICE) AS TOTALSPENT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
        ON C.C_CUSTKEY = O.O_CUSTKEY
    GROUP BY C.C_NAME
$$;

--call the CUSTOMERORDERS table UDF
SELECT *
FROM TABLE(CUSTOMERORDERS());

--create an overloaded SQL table UDF that accepts a customer name
CREATE FUNCTION CUSTOMERORDERS(CUSTOMERNAME STRING)
RETURNS TABLE(CUSTOMERNAME STRING, TOTALSPENT NUMBER(12,2))
AS
$$
    SELECT
        C.C_NAME AS CUSTOMERNAME,
        SUM(O.O_TOTALPRICE) AS TOTALSPENT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
        ON C.C_CUSTKEY = O.O_CUSTKEY
    WHERE C.C_NAME = CUSTOMERNAME
    GROUP BY C.C_NAME
$$;

--show overloaded functions
SHOW FUNCTIONS LIKE '%CUSTOMERORDERS%';

--call the parameterized table UDF
SELECT *
FROM TABLE(CUSTOMERORDERS('Customer#000062993'));
