--create the production database and source schema
CREATE DATABASE PRODUCTION_DB;
CREATE SCHEMA SRC_DATA;

--create inventory table
CREATE TABLE INVENTORY AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.INVENTORY
LIMIT 100000;

--create item table
CREATE TABLE ITEM AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM
LIMIT 100000;

--create access layer schema
USE DATABASE PRODUCTION_DB;

CREATE SCHEMA ACCESS_LAYER;

--create store sales table
CREATE TABLE STORE_SALES AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES
LIMIT 100000;

--capture the current timestamp before adding more data
SELECT CURRENT_TIMESTAMP;

--validate initial row counts
SELECT COUNT(*)
FROM PRODUCTION_DB.SRC_DATA.INVENTORY;

SELECT COUNT(*)
FROM PRODUCTION_DB.SRC_DATA.ITEM;

SELECT COUNT(*)
FROM PRODUCTION_DB.ACCESS_LAYER.STORE_SALES;

--insert additional inventory data
INSERT INTO PRODUCTION_DB.SRC_DATA.INVENTORY
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.INVENTORY
LIMIT 20000;

--insert additional item data
INSERT INTO PRODUCTION_DB.SRC_DATA.ITEM
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM
LIMIT 20000;

--insert additional store sales data
INSERT INTO PRODUCTION_DB.ACCESS_LAYER.STORE_SALES
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES
LIMIT 20000;

--clone the production database as it existed at a specific timestamp
CREATE DATABASE DEV_1
CLONE PRODUCTION_DB AT
(
    TIMESTAMP => '<replace with the timestamp from the earlier step>'::TIMESTAMP_TZ
);

--validate cloned row counts
SELECT COUNT(*)
FROM DEV_1.SRC_DATA.INVENTORY;

SELECT COUNT(*)
FROM DEV_1.SRC_DATA.ITEM;

SELECT COUNT(*)
FROM DEV_1.ACCESS_LAYER.STORE_SALES;
