--create the production database and schemas
CREATE DATABASE PRD;

CREATE SCHEMA SRC_DATA;
CREATE SCHEMA INTEGRATED_DATA;
CREATE SCHEMA REPORTING_DATA;

--create source customer table
USE SCHEMA SRC_DATA;

CREATE TABLE CUSTOMER AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

--create source lineitem table
USE SCHEMA SRC_DATA;

CREATE TABLE LINEITEM AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

--create integrated orders table
USE SCHEMA INTEGRATED_DATA;

CREATE TABLE ORDERS AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

--create reporting view
USE SCHEMA REPORTING_DATA;

CREATE VIEW REVENUE_REPORT AS
SELECT
    L_RETURNFLAG,
    L_LINESTATUS,
    SUM(L_QUANTITY) AS SUM_QTY,
    SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT) * (1 + L_TAX)) AS SUM_CHARGE,
    AVG(L_QUANTITY) AS AVG_QTY,
    AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
    AVG(L_DISCOUNT) AS AVG_DISC,
    COUNT(*) AS COUNT_ORDER
FROM PRD.SRC_DATA.LINEITEM
WHERE L_SHIPDATE <= DATEADD(DAY, -90, TO_DATE('1998-12-01'))
GROUP BY
    L_RETURNFLAG,
    L_LINESTATUS;

--clone production into a development environment
CREATE DATABASE DEV_DB_1
CLONE PRD;

--validate data in the cloned table
SELECT COUNT(*)
FROM DEV_DB_1.SRC_DATA.CUSTOMER;

--validate data in the cloned view
SELECT COUNT(*)
FROM DEV_DB_1.REPORTING_DATA.REVENUE_REPORT;

--create a testing environment from production
CREATE DATABASE TEST_1
CLONE PRD;

--create another development environment from the first development clone
CREATE DATABASE DEV_DB_2
CLONE DEV_DB_1;
