--verify that the CUSTOMER_DATA table exists
USE ROLE SYSADMIN;

SELECT *
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA;

--ensure the policy administrator can create row access policies
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE SECURITYADMIN;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE SECURITYADMIN;

--create roles that represent row-level access
USE ROLE USERADMIN;

CREATE OR REPLACE ROLE REGION_EAST;
CREATE OR REPLACE ROLE REGION_WEST;
CREATE OR REPLACE ROLE REGION_ALL;

--grant exactly one region role to the test user when testing
USE ROLE SECURITYADMIN;

GRANT ROLE REGION_EAST TO USER <YOUR_USER_NAME>;

--optional alternatives for testing:
--GRANT ROLE REGION_WEST TO USER <YOUR_USER_NAME>;
--GRANT ROLE REGION_ALL TO USER <YOUR_USER_NAME>;

--if testing a different region role, revoke the previous role first
--REVOKE ROLE REGION_EAST FROM USER <YOUR_USER_NAME>;
--GRANT ROLE REGION_WEST TO USER <YOUR_USER_NAME>;

--grant the privilege required to apply row access policies
USE ROLE ACCOUNTADMIN;

GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE SECURITYADMIN;

--create the row access policy
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROW ACCESS POLICY GOVERNANCE_DB.SECURITY.REGION_FILTER_POLICY
    AS (REGION_VAL STRING) RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('REGION_ALL') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('REGION_EAST') THEN REGION_VAL = 'EAST'
        WHEN IS_ROLE_IN_SESSION('REGION_WEST') THEN REGION_VAL = 'WEST'
        ELSE FALSE
    END;

--attach the row access policy to the REGION column
USE ROLE SECURITYADMIN;

ALTER TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
    ADD ROW ACCESS POLICY GOVERNANCE_DB.SECURITY.REGION_FILTER_POLICY
    ON (REGION);

--test the row access policy alongside masking controls
USE ROLE PII_MASKED;

SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    REGION
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
ORDER BY CUSTOMER_ID;
