CREATE OR REPLACE WAREHOUSE WH_QAS_TEST
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCDS_SF10TCL;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

USE WAREHOUSE WH_QAS_TEST;

SELECT
    SS_STORE_SK,
    SUM(SS_SALES_PRICE) AS TOTAL_SALES
FROM STORE_SALES
GROUP BY SS_STORE_SK
ORDER BY TOTAL_SALES DESC;

SELECT LAST_QUERY_ID();

SELECT PARSE_JSON(SYSTEM$ESTIMATE_QUERY_ACCELERATION('<query_id>'));

ALTER WAREHOUSE WH_QAS_TEST
SET ENABLE_QUERY_ACCELERATION = TRUE;

ALTER WAREHOUSE WH_QAS_TEST
SET QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2;

SELECT
    SS_STORE_SK,
    SUM(SS_SALES_PRICE) AS TOTAL_SALES
FROM STORE_SALES
WHERE SS_SOLD_DATE_SK BETWEEN 2450815 AND 2451179
GROUP BY SS_STORE_SK
ORDER BY TOTAL_SALES DESC;

--identify additional candidate queries for QAS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ACCELERATION_ELIGIBLE;
