--create a database for the views
CREATE OR REPLACE DATABASE TEST_VIEW_CREATION;

--create a standard view that aggregates order data by commit date
CREATE OR REPLACE VIEW TEST_VIEW_CREATION.PUBLIC.DATE_WISE_PROFIT
AS
SELECT
    L_COMMITDATE AS ORDER_DATE,
    SUM(L_QUANTITY) AS TOTAL_QUANTITY,
    SUM(L_EXTENDEDPRICE) AS TOTAL_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM
GROUP BY L_COMMITDATE;

--query the standard view
SELECT *
FROM TEST_VIEW_CREATION.PUBLIC.DATE_WISE_PROFIT;

--create a materialized view for faster repeated access
CREATE OR REPLACE MATERIALIZED VIEW TEST_VIEW_CREATION.PUBLIC.DATE_WISE_ORDER_FAST
AS
SELECT
    L_COMMITDATE AS ORDER_DATE,
    SUM(L_QUANTITY) AS TOTAL_QUANTITY,
    SUM(L_EXTENDEDPRICE) AS TOTAL_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM
GROUP BY L_COMMITDATE;

--query the materialized view
SELECT *
FROM TEST_VIEW_CREATION.PUBLIC.DATE_WISE_ORDER_FAST;
