--provider account: create a reader account
USE ROLE ACCOUNTADMIN;

CREATE MANAGED ACCOUNT SH_NON_SF_ACCOUNT
    TYPE = READER,
    ADMIN_NAME = 'READER_ADMIN',
    ADMIN_PASSWORD = '<password_of_your_choice>';

--reader account: create a virtual warehouse
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE SP_VW
WITH
    WAREHOUSE_SIZE = 'SMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

--reader account: grant warehouse privileges
GRANT USAGE ON WAREHOUSE SP_VW TO ROLE PUBLIC;
GRANT ALL ON WAREHOUSE SP_VW TO ROLE SYSADMIN;

--provider account: create sample data
CREATE DATABASE CUSTOMER_DATA;

CREATE TABLE STORE_SALES AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES
LIMIT 1000;

--provider account: create a secure view
USE DATABASE CUSTOMER_DATA;

CREATE OR REPLACE SECURE VIEW STORE_SALES_AGG
AS
SELECT
    SS_SOLD_DATE_SK,
    SUM(SS_NET_PROFIT) AS SS_NET_PROFIT
FROM CUSTOMER_DATA.PUBLIC.STORE_SALES
GROUP BY 1;

--provider account: create a share
USE ROLE ACCOUNTADMIN;

CREATE SHARE SHARE_SALES_DATA;

--provider account: grant share privileges
GRANT USAGE ON DATABASE CUSTOMER_DATA TO SHARE SHARE_SALES_DATA;
GRANT USAGE ON SCHEMA CUSTOMER_DATA.PUBLIC TO SHARE SHARE_SALES_DATA;
GRANT SELECT ON VIEW CUSTOMER_DATA.PUBLIC.STORE_SALES_AGG TO SHARE SHARE_SALES_DATA;

--provider account: add the reader account to the share
ALTER SHARE SHARE_SALES_DATA
ADD ACCOUNT = <reader_account_name_here>;

--reader account: create a database from the share
USE ROLE ACCOUNTADMIN;

CREATE DATABASE SALES
FROM SHARE <provider_account_name_here>.SHARE_SALES_DATA;

--reader account: query the shared secure view
SELECT *
FROM SALES.PUBLIC.STORE_SALES_AGG;
