--create a database for SQL scalar UDFs
CREATE DATABASE C10_R1;

--create a scalar SQL UDF that squares an input value
CREATE FUNCTION SQUARE(VAL FLOAT)
RETURNS FLOAT
AS
$$
    VAL * VAL
$$;

--test the SQUARE UDF
SELECT SQUARE(5);

--create a scalar SQL UDF to calculate profit after tax
CREATE FUNCTION PROFIT_AFTER_TAX(COST FLOAT, REVENUE FLOAT)
RETURNS FLOAT
AS
$$
    (REVENUE - COST) * (1 - 0.1)
$$;

--test the PROFIT_AFTER_TAX UDF
SELECT PROFIT_AFTER_TAX(100, 120);

--use the scalar UDF in a SELECT list and WHERE clause
SELECT
    DD.D_DATE,
    SUM(PROFIT_AFTER_TAX(SS_WHOLESALE_COST, SS_SALES_PRICE)) AS REAL_PROFIT
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES SS
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM DD
    ON SS.SS_SOLD_DATE_SK = DD.D_DATE_SK
WHERE DD.D_DATE BETWEEN '2003-01-01' AND '2003-12-31'
  AND PROFIT_AFTER_TAX(SS_WHOLESALE_COST, SS_SALES_PRICE) < -50
GROUP BY DD.D_DATE;
