--create a database and schema
CREATE DATABASE C8_R3;
CREATE SCHEMA SCHEMA1;

--create a customer table in SCHEMA1
CREATE TABLE CUSTOMER AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
LIMIT 100000;

--create a customer address table in SCHEMA1
CREATE TABLE CUSTOMER_ADDRESS AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS
LIMIT 100000;

--create a second schema
USE DATABASE C8_R3;

CREATE SCHEMA SCHEMA2;

--create an inventory table in SCHEMA2
CREATE TABLE INVENTORY AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.INVENTORY
LIMIT 100000;

--drop the customer table
USE SCHEMA SCHEMA1;

DROP TABLE CUSTOMER;

--identify dropped tables using metadata
USE ROLE ACCOUNTADMIN;

SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    ID,
    CLONE_GROUP_ID,
    TABLE_CREATED,
    TABLE_DROPPED
FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG = 'C8_R3';

--restore the dropped customer table
USE SCHEMA SCHEMA1;

UNDROP TABLE CUSTOMER;

--validate that the table has been restored
SELECT COUNT(*)
FROM CUSTOMER;

--drop SCHEMA1
DROP SCHEMA SCHEMA1;

--restore SCHEMA1
UNDROP SCHEMA SCHEMA1;
