USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE C11_R2;
USE DATABASE C11_R2;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE SALES (
    ORDER_ID NUMBER,
    CUSTOMER_NAME STRING,
    REGION STRING,
    SALES_AMOUNT NUMBER
);

INSERT INTO SALES VALUES
(1, 'John Smith', 'North', 1200),
(2, 'Jane Doe', 'South', 850),
(3, 'Mike Johnson', 'North', 640),
(4, 'Emily Davis', 'West', 1500),
(5, 'Chris Brown', 'South', 920);

SELECT REGION, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY REGION;

SELECT REGION, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM C11_R2.PUBLIC.SALES
GROUP BY REGION;
