--create a database and table for sensitive data
USE ROLE SYSADMIN;

CREATE DATABASE SENSITIVE_DATA;

CREATE TABLE SENSITIVE_DATA.PUBLIC.SALARY
(
    EMP_ID INTEGER,
    SALARY NUMBER
);

--create a custom HR role
USE ROLE SECURITYADMIN;

CREATE ROLE HR_ROLE;

--transfer ownership of the sensitive objects to HR_ROLE
GRANT OWNERSHIP ON TABLE SENSITIVE_DATA.PUBLIC.SALARY TO ROLE HR_ROLE;
GRANT OWNERSHIP ON SCHEMA SENSITIVE_DATA.PUBLIC TO ROLE HR_ROLE;
GRANT OWNERSHIP ON DATABASE SENSITIVE_DATA TO ROLE HR_ROLE;

--validate that SYSADMIN cannot access the sensitive table
USE ROLE SYSADMIN;

SELECT *
FROM SENSITIVE_DATA.PUBLIC.SALARY;

--validate that ACCOUNTADMIN cannot access the sensitive table
USE ROLE ACCOUNTADMIN;

SELECT *
FROM SENSITIVE_DATA.PUBLIC.SALARY;

--create a user and grant the HR role
USE ROLE SECURITYADMIN;

CREATE USER HR_USER1
    PASSWORD = 'Password123123'
    MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE HR_ROLE TO USER HR_USER1;

--test access as HR_USER1
USE ROLE HR_ROLE;

SELECT *
FROM SENSITIVE_DATA.PUBLIC.SALARY;
