--create a database for the materialized view example
CREATE DATABASE C6_R5;

--disable cached results for the session
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

--create the sensor data table
CREATE OR REPLACE TABLE SENSOR_DATA
(
    CREATE_TS BIGINT,
    SENSOR_ID BIGINT,
    SENSOR_READING INTEGER
);

--generate and insert demo sensor data
INSERT INTO SENSOR_DATA
SELECT
    (SEQ8())::BIGINT AS CREATE_TS,
    UNIFORM(1, 9999999, RANDOM(11111))::BIGINT AS SENSOR_ID,
    UNIFORM(1, 9999999, RANDOM(22222))::INTEGER AS SENSOR_READING
FROM TABLE(GENERATOR(ROWCOUNT => 1000000000))
ORDER BY CREATE_TS;

--cluster the table by CREATE_TS
ALTER TABLE SENSOR_DATA CLUSTER BY (CREATE_TS);

--query using the clustered CREATE_TS column
SELECT
    COUNT(*) AS CNT,
    AVG(SENSOR_READING) AS MEAN_SENSOR_READING
FROM SENSOR_DATA
WHERE CREATE_TS BETWEEN 100000000 AND 100001000;

--query using the unclustered SENSOR_ID column
SELECT
    COUNT(*) AS CNT,
    AVG(SENSOR_READING) AS MEAN_SENSOR_READING
FROM SENSOR_DATA
WHERE SENSOR_ID BETWEEN 100000 AND 101000;

--create a materialized view clustered by SENSOR_ID
CREATE OR REPLACE MATERIALIZED VIEW MV_SENSOR_READING
(
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
)
CLUSTER BY (SENSOR_ID)
AS
SELECT
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
FROM SENSOR_DATA;

--query the materialized view using SENSOR_ID
SELECT
    COUNT(*) AS CNT,
    AVG(SENSOR_READING) AS MEAN_SENSOR_READING
FROM MV_SENSOR_READING
WHERE SENSOR_ID BETWEEN 100000 AND 101000;

--optionally resize a warehouse before creating a materialized view
ALTER WAREHOUSE <NAME> SET WAREHOUSE_SIZE = XXXLARGE;

CREATE OR REPLACE MATERIALIZED VIEW MV_SENSOR_READING
(
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
)
CLUSTER BY (SENSOR_ID)
AS
SELECT
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
FROM SENSOR_DATA;

--resize the warehouse after materialized view creation
ALTER WAREHOUSE <NAME> SET WAREHOUSE_SIZE = MEDIUM;
