CREATE DATABASE C6_R5;
USE DATABASE C6_R5;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

CREATE OR REPLACE TABLE SENSOR_DATA
(
    CREATE_TS BIGINT,
    SENSOR_ID BIGINT,
    SENSOR_READING INTEGER
);

INSERT INTO SENSOR_DATA
SELECT
    (SEQ8())::BIGINT AS CREATE_TS,
    UNIFORM(1, 9999999, RANDOM(11111))::BIGINT AS SENSOR_ID,
    UNIFORM(1, 9999999, RANDOM(22222))::INTEGER AS SENSOR_READING
FROM TABLE(GENERATOR(ROWCOUNT => 1000000000))
ORDER BY CREATE_TS;

ALTER TABLE SENSOR_DATA CLUSTER BY (CREATE_TS);

SELECT
    COUNT(*) AS CNT,
    AVG(SENSOR_READING) AS MEAN_SENSOR_READING
FROM SENSOR_DATA
WHERE CREATE_TS BETWEEN 100000000 AND 100001000;

SELECT
    COUNT(*) AS CNT,
    AVG(SENSOR_READING) AS MEAN_SENSOR_READING
FROM SENSOR_DATA
WHERE SENSOR_ID BETWEEN 100000 AND 101000;

CREATE OR REPLACE MATERIALIZED VIEW MV_SENSOR_READING
(
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
)
CLUSTER BY (SENSOR_ID)
AS
SELECT
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
FROM SENSOR_DATA;

SELECT
    COUNT(*) AS CNT,
    AVG(SENSOR_READING) AS MEAN_SENSOR_READING
FROM MV_SENSOR_READING
WHERE SENSOR_ID BETWEEN 100000 AND 101000;

--optional warehouse resize pattern for materialized view creation
ALTER WAREHOUSE <NAME> SET WAREHOUSE_SIZE = XXXLARGE;

CREATE OR REPLACE MATERIALIZED VIEW MV_SENSOR_READING
(
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
)
CLUSTER BY (SENSOR_ID)
AS
SELECT
    CREATE_TS,
    SENSOR_ID,
    SENSOR_READING
FROM SENSOR_DATA;

ALTER WAREHOUSE <NAME> SET WAREHOUSE_SIZE = MEDIUM;
