--because this recipe builds on row-level security, grant REGION_ALL to the test user
--so all rows are visible during validation
USE ROLE SECURITYADMIN;

GRANT ROLE REGION_ALL TO USER <YOUR_USER_NAME>;

--verify the customer data table with full access to EMAIL values
USE ROLE PII_FULL;

SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    REGION
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
ORDER BY CUSTOMER_ID;

--ensure SECURITYADMIN can create tags in the schema
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE SECURITYADMIN;
GRANT CREATE TAG ON SCHEMA GOVERNANCE_DB.SECURITY TO ROLE SECURITYADMIN;

--create a sensitivity classification tag
USE ROLE SECURITYADMIN;

CREATE OR REPLACE TAG GOVERNANCE_DB.SECURITY.SENSITIVITY_LEVEL;

--remove the direct column-level masking policy so tag-based masking can take effect
ALTER TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
    MODIFY COLUMN EMAIL
    UNSET MASKING POLICY;

--assign the sensitivity tag to the EMAIL column
ALTER TABLE GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
    MODIFY COLUMN EMAIL
    SET TAG GOVERNANCE_DB.SECURITY.SENSITIVITY_LEVEL = 'CONFIDENTIAL';

--verify the tag assignment
SELECT *
FROM TABLE(
    GOVERNANCE_DB.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
        'GOVERNANCE_DB.SECURITY.CUSTOMER_DATA',
        'TABLE'
    )
)
WHERE COLUMN_NAME = 'EMAIL';

--associate the existing masking policy with the tag
ALTER TAG GOVERNANCE_DB.SECURITY.SENSITIVITY_LEVEL
    SET MASKING POLICY GOVERNANCE_DB.SECURITY.EMAIL_MASK;

--test tag-based masking with the masked role
USE ROLE PII_MASKED;

SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    REGION
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
ORDER BY CUSTOMER_ID;

--test tag-based masking with the full access role
USE ROLE PII_FULL;

SELECT
    CUSTOMER_ID,
    FULL_NAME,
    EMAIL,
    REGION
FROM GOVERNANCE_DB.SECURITY.CUSTOMER_DATA
ORDER BY CUSTOMER_ID;
