--sample aggregation query
SELECT
    C.C_NAME,
    SUM(L_EXTENDEDPRICE),
    SUM(L_TAX)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
    ON O.O_CUSTKEY = C.C_CUSTKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LI
    ON LI.L_ORDERKEY = O.O_ORDERKEY
GROUP BY C.C_NAME;

--create the target database and table
USE ROLE SYSADMIN;

CREATE DATABASE TASK_TREE_DEMO;
USE DATABASE TASK_TREE_DEMO;

CREATE TABLE ORDERING_CUSTOMERS
(
    CUSTOMER_NAME STRING,
    REVENUE NUMBER(16,2),
    TAX NUMBER(16,2)
);

--create the root task that clears the target table
CREATE TASK CLEAR_ORDERING_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
    COMMENT = 'Delete from ORDERING_CUSTOMERS'
AS
    DELETE FROM ORDERING_CUSTOMERS;

--create the child task that inserts refreshed data
CREATE TASK INSERT_ORDERING_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
    COMMENT = 'Insert into ORDERING_CUSTOMERS the latest data'
AS
    INSERT INTO ORDERING_CUSTOMERS
    SELECT
        C.C_NAME,
        SUM(L_EXTENDEDPRICE),
        SUM(L_TAX)
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
        ON O.O_CUSTKEY = C.C_CUSTKEY
    INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LI
        ON LI.L_ORDERKEY = O.O_ORDERKEY
    GROUP BY C.C_NAME;

--connect the child task to the root task
ALTER TASK INSERT_ORDERING_CUSTOMERS
ADD AFTER CLEAR_ORDERING_CUSTOMERS;

--validate predecessor relationship
DESC TASK INSERT_ORDERING_CUSTOMERS;

--schedule the root task
ALTER TASK CLEAR_ORDERING_CUSTOMERS
SET SCHEDULE = '10 MINUTE';

--grant task execution privileges if needed
USE ROLE ACCOUNTADMIN;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

--resume child tasks first, then parent tasks
USE ROLE SYSADMIN;

ALTER TASK INSERT_ORDERING_CUSTOMERS RESUME;
ALTER TASK CLEAR_ORDERING_CUSTOMERS RESUME;

--monitor task history for the task tree
SELECT
    NAME,
    STATE,
    COMPLETED_TIME,
    SCHEDULED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME IN ('CLEAR_ORDERING_CUSTOMERS','INSERT_ORDERING_CUSTOMERS');

--validate task tree output
SELECT *
FROM ORDERING_CUSTOMERS;
