--query execution history for all tasks
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME;

--query task history between two timestamps
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => TO_TIMESTAMP_LTZ('2020-08-13 14:00:00.000 -0700'),
    SCHEDULED_TIME_RANGE_END => TO_TIMESTAMP_LTZ('2020-08-13 14:10:00.000 -0700')
))
ORDER BY SCHEDULED_TIME;

--limit the number of task history rows returned
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    RESULT_LIMIT => 5
))
ORDER BY SCHEDULED_TIME;

--query task history by task name
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'CLEAR_ORDERING_CUSTOMERS'
))
ORDER BY SCHEDULED_TIME;

--combine task name and result limit filters
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'CLEAR_ORDERING_CUSTOMERS',
    RESULT_LIMIT => 2
))
ORDER BY SCHEDULED_TIME;
