CREATE OR REPLACE WAREHOUSE WH_SCALE_TEST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCDS_SF10TCL;
USE WAREHOUSE WH_SCALE_TEST;

SELECT
    D_YEAR,
    SUM(SS_SALES_PRICE) AS TOTAL_SALES
FROM STORE_SALES
JOIN DATE_DIM
    ON STORE_SALES.SS_SOLD_DATE_SK = DATE_DIM.D_DATE_SK
GROUP BY D_YEAR
ORDER BY D_YEAR;

--example horizontal scaling configuration for a multi-cluster warehouse
ALTER WAREHOUSE WH_SCALE_TEST
SET MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = STANDARD;

--example vertical scaling configuration
ALTER WAREHOUSE WH_SCALE_TEST
SET WAREHOUSE_SIZE = 'MEDIUM';
