--query sample orders
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS
SAMPLE ROW (1000 ROWS);

--perform a simple count by order priority
SELECT
    O_ORDERPRIORITY,
    COUNT(O_CUSTKEY)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS
GROUP BY 1
ORDER BY 1;

--disable cached results for distinct-count comparison
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

--perform an exact distinct count by order priority
SELECT
    O_ORDERPRIORITY,
    COUNT(DISTINCT O_CUSTKEY)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.ORDERS
GROUP BY 1
ORDER BY 1;

--perform an approximate distinct count by order priority
SELECT
    O_ORDERPRIORITY,
    APPROX_COUNT_DISTINCT(O_CUSTKEY)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS
GROUP BY 1
ORDER BY 1;
