--create the database and interim processing table
CREATE DATABASE C6_R4;

CREATE TABLE LINEITEM_INTERIM_PROCESSING
(
    L_ORDERKEY NUMBER(38,0),
    L_PARTKEY NUMBER(38,0),
    L_SUPPKEY NUMBER(38,0),
    L_LINENUMBER NUMBER(38,0),
    L_QUANTITY NUMBER(12,2),
    L_EXTENDEDPRICE NUMBER(12,2),
    L_DISCOUNT NUMBER(12,2),
    L_TAX NUMBER(12,2),
    L_RETURNFLAG VARCHAR(1),
    L_LINESTATUS VARCHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT VARCHAR(25),
    L_SHIPMODE VARCHAR(10),
    L_COMMENT VARCHAR(44)
);

--create the reporting table
CREATE TABLE ORDER_REPORTING
(
    ORDER_SHIP_DATE DATE,
    QUANTITY NUMBER(38,2),
    PRICE NUMBER(38,2),
    DISCOUNT NUMBER(38,2)
);

--clear interim processing data
DELETE FROM LINEITEM_INTERIM_PROCESSING;

--load interim processing data from sample data
INSERT INTO LINEITEM_INTERIM_PROCESSING
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
WHERE L_SHIPDATE BETWEEN DATEADD(DAY, -365, TO_DATE('1998-12-31'))
                     AND TO_DATE('1998-12-31');

--delete the last 7 days of reporting data
DELETE FROM ORDER_REPORTING
WHERE ORDER_SHIP_DATE > DATEADD(DAY, -7, TO_DATE('1998-12-01'));

--insert aggregated data into the reporting table
INSERT INTO ORDER_REPORTING
SELECT
    L_SHIPDATE AS ORDER_SHIP_DATE,
    SUM(L_QUANTITY) AS QUANTITY,
    SUM(L_EXTENDEDPRICE) AS PRICE,
    SUM(L_EXTENDEDPRICE) AS DISCOUNT
FROM LINEITEM_INTERIM_PROCESSING
WHERE ORDER_SHIP_DATE NOT IN
    (
        SELECT ORDER_SHIP_DATE
        FROM ORDER_REPORTING
    )
GROUP BY ORDER_SHIP_DATE;

--delete interim processing data after use
DELETE FROM LINEITEM_INTERIM_PROCESSING;

--review storage metrics after metadata refresh
USE ROLE ACCOUNTADMIN;

SELECT *
FROM C6_R4.INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG = 'C6_R4';

--recreate the interim processing table as transient
DROP TABLE LINEITEM_INTERIM_PROCESSING;

CREATE TRANSIENT TABLE LINEITEM_INTERIM_PROCESSING
(
    L_ORDERKEY NUMBER(38,0),
    L_PARTKEY NUMBER(38,0),
    L_SUPPKEY NUMBER(38,0),
    L_LINENUMBER NUMBER(38,0),
    L_QUANTITY NUMBER(12,2),
    L_EXTENDEDPRICE NUMBER(12,2),
    L_DISCOUNT NUMBER(12,2),
    L_TAX NUMBER(12,2),
    L_RETURNFLAG VARCHAR(1),
    L_LINESTATUS VARCHAR(1),
    L_SHIPDATE DATE,
    L_COMMITDATE DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT VARCHAR(25),
    L_SHIPMODE VARCHAR(10),
    L_COMMENT VARCHAR(44)
);
