--switch to the SECURITYADMIN role
USE ROLE SECURITYADMIN;

--create a new administrative user
CREATE USER SECONDARY_ACCOUNT_ADMIN
 PASSWORD = 'Snowflake@123'
 DEFAULT_ROLE = ACCOUNTADMIN
 MUST_CHANGE_PASSWORD = TRUE;

--grant the ACCOUNTADMIN role
GRANT ROLE ACCOUNTADMIN TO USER SECONDARY_ACCOUNT_ADMIN;

--verify grants
SHOW GRANTS TO USER SECONDARY_ACCOUNT_ADMIN;
